apiVersion: v1 # for versions before 1.6.0 use extensions/v1beta1
kind: ReplicationController
metadata:
  name: odoo-repctl
spec:
  replicas: 2
  selector:
    name: odoo-repctl
    version: v1
  template:
    metadata:
      labels:
        name: odoo-repctl
        version: v1
    spec:
      containers:
      - name: db
        image: postgres:9.4
        ports:
        - containerPort: 5432
      - name: web
        image: odoo
        ports:
        - containerPort: 8069